version: "3.8" # Use the appropriate version of Docker Compose

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "9009:9009" # Map port 8000 inside the container to port 9002 on the host
    environment:
      - DJANGO_SETTINGS_MODULE=inference_service.settings
      - POSTGRES_DB=amaz_ai_chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Intern2024
      - POSTGRES_HOST=192.168.1.45 #db
      - POSTGRES_PORT=5432

    # depends_on:
    #   - db
    networks:
      - shared_network

  # db:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=amaz_ai_chatbot
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=Intern2024
  #     - POSTGRES_HOST=localhost
  #     - POSTGRES_PORT=5432
  #   networks:
  #     - all

networks:
  shared_network:
    external: true
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
